### ISSUE TITLE
使用服务端 DNS 进行解析

### ISSUE THREAD

**Issue by Mythologyli** [githuu5y5u/EasierConnect#1]
您好！非常感谢您在 EasierConnect 项目中的贡献。有一个问题想要请教一下。

根据我的测试，原版 EasyConnect 客户端似乎劫持了本地 DNS。通过官方文件也能发现，可以通过内网 DNS 服务器进行解析。
[SANGFOR_SSLVPN_v7.1_内网域名解析配置指导.pdf](https://github.com/githuu5y5u/EasierConnect/files/10568614/SANGFOR_SSLVPN_v7.1_.pdf)

而目前项目中在 DnsRule 之外的解析都是由本地 DNS 服务器进行的。DnsRule 应该对应上面文件中“内网没有DNS服务器，通过添加域名发布资源”的情况。而本人学校的许多内网资源需要通过内网 DNS 解析才能正常访问，而这部分域名没有被添加在 DnsRule 中。

有没有可能实现通过服务端 DNS 进行解析呢？还请赐教。

**Comment by githuu5y5u** [comment]
lyc8503 大佬的项目又开了， 不清楚什么情况。。。。
